version: "3.9"
services:
  mysql:
    image: mysql:8.0
    hostname: bottle-note-mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: bottle_note
      MYSQL_USER: bottle_note
      MYSQL_PASSWORD: bottle_note_1234
    ports:
      - "23306:3306"
    networks:
      - network
  redis:
    image: redis:6.2.6-alpine
    container_name: bottle-note-redis
    ports:
      - "26379:6379"
    networks:
      - network
networks:
  network:
    driver: bridge
